# Generated by Django 2.0.7 on 2022-12-31 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='house_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.TextField(default='')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='house_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(default='')),
                ('phone_number', models.TextField(default='')),
                ('longitude', models.TextField(default='')),
                ('latitude', models.TextField(default='')),
                ('location', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('additional_info', models.TextField(default='')),
                ('booker_name', models.TextField(default='')),
                ('booked_by_user_id', models.IntegerField(default=0)),
                ('no_of_rooms', models.IntegerField(default=0)),
                ('no_of_bath', models.IntegerField(default=0)),
                ('no_of_kitchen', models.IntegerField(default=0)),
                ('is_electricity', models.BooleanField(default=False)),
                ('is_water', models.BooleanField(default=False)),
                ('is_gas', models.BooleanField(default=False)),
                ('is_internet', models.BooleanField(default=False)),
                ('is_furnished', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('booking_date', models.DateTimeField(blank=True, null=True)),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='house_video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_path', models.TextField(default='')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.house_info')),
            ],
        ),
        migrations.AddField(
            model_name='house_images',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.house_info'),
        ),
    ]
