# Generated by Django 2.0.7 on 2023-01-01 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_house_info_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='house_info',
            name='square_fit',
            field=models.IntegerField(default=0),
        ),
    ]
