# Generated by Django 2.0.7 on 2023-01-01 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_house_info_square_fit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house_info',
            name='square_fit',
            field=models.TextField(default=0),
        ),
    ]
