# Generated by Django 2.0.7 on 2023-01-01 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20230101_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house_info',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='house_info',
            name='longitude',
        ),
    ]
