# Generated by Django 2.0.7 on 2023-01-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20230101_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house_info',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
