# Generated by Django 2.0.7 on 2023-01-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20230102_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house_info',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
