# Generated by Django 2.0.7 on 2022-12-31 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=256),
        ),
    ]
