# Generated by Django 2.0.7 on 2023-01-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen_app', '0003_alter_customuser_first_name_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
